[package]
name = "window"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform window setup and render"
license = "MIT"
build = "build.rs"

[dev-dependencies]
pretty_env_logger = "0.4"

[dependencies]
async-task = "4.0"
anyhow = "1.0"
config = { path = "../config" }
thiserror = "1.0"
bitflags = "1.0"
euclid = "0.22"
guillotiere = "0.6"
lazy_static = "1.4"
libloading = "0.6"
line_drawing = "0.8"
log = "0.4"
metrics = { version="0.14", features=["std"]}
promise = { path = "../promise" }
raw-window-handle = "0.3"
resize = "0.5"
serde = {version="1.0", features = ["rc", "derive"]}
glium = { version = "0.28", default-features = false}
wezterm-input-types = { path = "../wezterm-input-types" }
wgpu = "0.7"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [
    "dwmapi",
    "handleapi",
    "imm",
    "libloaderapi",
    "synchapi",
    "winerror",
    "winuser",
]}
winreg = "0.6"
clipboard-win = "2.2"
shared_library = "0.1"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
dirs-next = "2.0"
filedescriptor = { version="0.7", path = "../filedescriptor" }
x11 = {version ="2.18", features = ["xlib_xcb"]}
xcb = {version="0.9", features=["render", "xkb", "xlib_xcb"]}
xcb-util = { features = [ "cursor", "image", "icccm", "ewmh", "keysyms"], version = "0.3" }
xkbcommon = { version = "0.5", features = ["x11", "wayland"], git="https://github.com/wez/xkbcommon-rs.git", rev="01a0a0cd5663405e6e4abb1ad3add9add1496f58"}
mio = "0.6"
libc = "0.2"
#smithay-client-toolkit = {version = "0.9", features=["calloop"], git="https://github.com/wez/client-toolkit.git", branch="title_trunc"}
smithay-client-toolkit = {version = "0.12", features=["calloop"]}
memmap = "0.7"
wayland-client = {version="0.28", features=["use_system_lib"]}

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.20"
objc = "0.2"
clipboard = "0.5"
core-foundation = "0.7"
core-graphics = "0.19"
